### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
"make":"honda",
"model":"crv",
"year": 2021,
"mileage": 2000,
"lng": 0,
"lat": 0,
"price": 100000
}


### Approve a report

PATCH  http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved":true
}

### Get an estimate for a car

Get  http://localhost:3000/reports?make=honda&model=crv&lng=0&lat=0&mileage=1000&year=2000
Content-Type: application/json
