### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
"make":"ford",
"model":"mustang",
"year": 2020,
"mileage": 2000,
"lng": 0,
"lat": 0,
"price": 20000
}


### Approve a report

PATCH  http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved":true
}

### Get an estimate for a car

Get  http://localhost:3000/reports?make=ford&model=mustang&lng=0&lat=0&mileage=20000&year=2020
Content-Type: application/json
