
### Create a new user
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "b@b.com",
    "password":"1234567"
}

### Sign in user
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "b@b.com",
    "password":"1234567"
}


### Get Current user
GET  http://localhost:3000/auth/whoami HTTP/1.1
content-type: application/json


### Sign out
POST   http://localhost:3000/auth/signout HTTP/1.1
content-type: application/json


### Get a particular user
GET  http://localhost:3000/auth/5 HTTP/1.1
content-type: application/json


###  Find all users with given email
GET  http://localhost:3000/auth?email=test@tesst.com HTTP/1.1
content-type: application/json


###  Delete User with given id
DELETE  http://localhost:3000/auth/1 HTTP/1.1
content-type: application/json


###  Update User with given id
PATCH http://localhost:3000/auth/3 HTTP/1.1
content-type: application/json

{"email":"aaaa@aaaa.com"}

